on:
  workflow_dispatch:
  schedule:
    - cron: '5 5 * * *'

name: Scala Steward

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    runs-on: ubuntu-22.04
    name: Scala Steward
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
      - name: Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
